--From the table PUBLISHER, AUTHOR and BOOK perform the following queries:  

--Part – A: 
SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK
--1. List all books with their authors. 
SELECT TITLE, AUTHORNAME FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--2. List all books with their publishers. 
SELECT TITLE, PUBLISHERNAME FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--3. List all books with their authors and publishers. 
SELECT TITLE, AUTHORNAME, PUBLISHERNAME FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--4. List all books published after 2010 with their authors and publisher and price.
SELECT TITLE, AUTHORNAME, PUBLISHERNAME, PRICE, PUBLICATIONYEAR FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
WHERE PUBLICATIONYEAR > 2010

--5. List all authors and the number of books they have written. 
SELECT AUTHORNAME, COUNT(A.AUTHORID) AS NOOFBOOKS FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME

--6. List all publishers and the total price of books they have published. 
SELECT PUBLISHERNAME, SUM(B.PRICE) AS NOOFBOOKS FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME

--7. List authors who have not written any books. 
SELECT * FROM AUTHOR A 
LEFT JOIN BOOK B
ON B.AUTHORID = A.AUTHORID
WHERE BOOKID IS NULL

--8. Display the total number of books written by each author along with the average price of their books. 
SELECT AUTHORNAME, COUNT(A.AUTHORID) AS NOOFBOOKS, AVG(B.PRICE) AS AVGPRICE 
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest. 
SELECT PUBLISHERNAME, COUNT(P.PUBLISHERID) AS NOOFBOOKS FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME 
ORDER BY COUNT(P.PUBLISHERID) DESC

--10. Display number of books published each year.
SELECT PUBLICATIONYEAR, COUNT(B.BOOKID) AS NOOFBOOKS 
FROM BOOK B
GROUP BY PUBLICATIONYEAR

--Part – B: 

--11. List the publishers whose total book prices exceed 500, ordered by the total price. 
SELECT PUBLISHERNAME, SUM(B.PRICE) AS TOTAL_PRICE 
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME 
HAVING SUM(B.PRICE) > 500
ORDER BY SUM(B.PRICE)

--12. List most expensive book for each author, sort it with the highest price. 
SELECT AUTHORNAME, MAX(B.PRICE) AS MAXPRICE 
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME
ORDER BY MAX(B.PRICE) DESC

--13. Display publisher name and difference between maximum and minimum book price.
SELECT PUBLISHERNAME, MAX(B.PRICE)-MIN(B.PRICE) AS DIFF FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME 

--14. List publisher name and total price of books published each year. 
SELECT PUBLISHERNAME, PUBLICATIONYEAR, SUM(B.PRICE) AS NOOFBOOKS 
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLICATIONYEAR, PUBLISHERNAME

--15. Display author name and total price of books sorted by highest total price.
SELECT AUTHORNAME, SUM(B.PRICE) AS NOOFBOOKS 
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(B.PRICE) DESC

-- NEW TABLE
CREATE TABLE EMPLOYEE_MASTER (
	EMPLOYEENO VARCHAR(10) PRIMARY KEY,
	NAME VARCHAR(20), 
	MANAGERNO VARCHAR(10)
)

INSERT INTO EMPLOYEE_MASTER (EMPLOYEENO, NAME, MANAGERNO)
VALUES
('E01', 'Tarun', NULL),
('E02', 'Rohan', 'E02'),
('E03', 'Priya', 'E01'),
('E04', 'Milan', 'E03'),
('E05', 'Jay', 'E01'),
('E06', 'Anjana', 'E04');

SELECT * FROM EMPLOYEE_MASTER

--From the above table EMPLOYEE_MASTER perform the following queries:  

--Part – C: 

--16. Retrieve the names of employee along with their manager’s name from the Employee table. 
SELECT E1.NAME AS EMPS, E2.NAME AS MANAGER
FROM EMPLOYEE_MASTER E1
INNER JOIN EMPLOYEE_MASTER E2
ON E1.EMPLOYEENO = E2.MANAGERNO

--17. Display employees who are managers. 
SELECT E2.NAME AS MANAGER
FROM EMPLOYEE_MASTER E1
INNER JOIN EMPLOYEE_MASTER E2
ON E1.EMPLOYEENO = E2.MANAGERNO

--18. Display number of employees working under each manager. 
SELECT MANAGERNO, COUNT(*) AS EMPCOUNT
FROM EMPLOYEE_MASTER
WHERE MANAGERNO IS NOT NULL
GROUP BY MANAGERNO

--19. Display the employee’s name along with their manager’s name and senior manager name. 
SELECT E.NAME AS EMP, M.NAME AS MAN, SM.NAME AS SMAN
FROM EMPLOYEE_MASTER E
LEFT JOIN EMPLOYEE_MASTER M 
ON E.MANAGERNO = M.EMPLOYEENO
LEFT JOIN EMPLOYEE_MASTER SM 
ON M.MANAGERNO = SM.EMPLOYEENO

--20. Display managers and count of employees under them in descending order. 
SELECT E2.NAME AS MANAGER, COUNT(E1.EMPLOYEENO) AS EMPCOUNT 
FROM EMPLOYEE_MASTER E2
JOIN EMPLOYEE_MASTER E1
ON E1.MANAGERNO = E2.EMPLOYEENO
GROUP BY E2.NAME
ORDER BY COUNT(E1.EMPLOYEENO) DESC